events {
}
   http 
       {

        server
	{

               listen 443 ssl;
             
                server_name oelbied.42.fr;
			
		ssl_certificate /etc/nginx/ssl/oelbied.42.fr.crt;
             
                ssl_certificate_key /etc/nginx/ssl/oelbied.42.fr.key;

		root /var/www/html;
			
		index index.php;

		location /
		{
		   try_files $uri $uri/ /index.php?$args;
		}

		location ~ \.php$
		 {
		     fastcgi_pass wordpress:9000;

		    fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
			
		    include fastcgi_params;
		}
            }

       }


